CC=gcc
CFLAGS=-Wall


all: program1 program2 zadanie

program1: program1.c
	$(CC) $(CFLAGS) $(LFLAGS) program1.c -o program1
program2: program2.c
	$(CC) $(CFLAGS) $(LFLAGS) program2.c -o program2
zadanie: zadanie.c
	$(CC) $(CFLAGS) $(LFLAGS) zadanie.c -o zadanie
clean:
	rm -f program1 program2 zadanie
	
    
		